### POST /api/add/post
# Cette requête permet d'ajouter un article
POST http://127.0.0.1:8000/api/add/post
Content-Type: application/json
Authorization: Bearer 7|ORp2tUsMeXlQU35es2yPqkw2J0rx0m6xd4dD7tu90f90c8ee

//{
//  "title": "Mon article 7",
//  "slug": "mon-article-7",
//  "description": "Ceci est mon contenu pour mon article 7"
//}

{
  "title": "TailwindCSS 4",
  "description": "Une configuration via le fichier CSS et non plus en JS"
}


###
# @name POST /api/edit/post/{slug}-{id}
# Cette requête permet d'ajouter un article
POST http://127.0.0.1:8000/api/edit/post/mon-article-2-2
Content-Type: application/json
Authorization: Bearer 7|ORp2tUsMeXlQU35es2yPqkw2J0rx0m6xd4dD7tu90f90c8ee

//{
//  "title": "Mon article 2",
//  "slug": "mon-article-deux",
//  "description": "Mise à jour du contenu de mon article 2"
//}

{
  "title": "Mon article deux",
  "description": "Mise à jour du contenu de mon article 2"
}

###
# @name GET /api/posts
# Cette requête permet de récupérer tous les articles
GET http://127.0.0.1:8000/api/posts

###
# @name GET /api/posts/{id}
# Cette requête permet de récupérer un seul article
GET http://127.0.0.1:8000/api/posts/12

###
# @name DELETE /api/posts/{id}
# Cette requête permet de supprimer un article
DELETE http://127.0.0.1:8000/api/posts/8
Authorization: Bearer 7|ORp2tUsMeXlQU35es2yPqkw2J0rx0m6xd4dD7tu90f90c8ee
